### ISSUE TITLE
Error in processing data

### ISSUE THREAD

**Issue by yzli1998** [Jixuan-Fan/Momentum-GS#6]
Thank you for your outstanding work. I finished downloading Mill 19 (Building, Rubble) and encountered an error when executing the instruction "bashscript/data _ preparation/preprocess _ Mill19.sh". Do you know the reason?

Rename image folders done.
Copy Colmap results done.
Copy partition files done.
1it [00:00, 82.66it/s]
Traceback (most recent call last):
  File "tools/transform_pt2txt.py", line 69, in <module>
    f.write('# Number of images: {}\n'.format(len(os.listdir(sparse_path.parent / 'input'))))
FileNotFoundError: [Errno 2] No such file or directory: 'data/mill19/building-pixsfm/train/input'
Preprocess Mill19 done

**Comment by Jixuan-Fan** [comment]
Hi @Pepper-FlavoredChewingGum,
I have fixed the bug (`transform_pt2txt.py` is unnecessary). If you encounter any further issues, please feel free to let me know.
